project: poseidon

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  banner:
    charset: UTF-8
  mvc:
    static-path-pattern: /static/**


  jpa:
    hibernate:
      ddl-auto: update #新增数据库链接必备的参数
    show-sql: false

  kafka:
    bootstrap-server: 127.0.0.1:9092
    listener:
      concurrency: 3
    producer:
      retries: 0
      acks: all
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: latest

server:
  port: 80
  servlet:
    context-path: /${project}
  tomcat:
    uri-encoding: utf-8

#-------------自定义配置-------------
kafka:
  topic:
    realtime: sampleMsg

jedis :
  pool :
    host : 127.0.0.1
    port : 6379
    config :
      maxTotal: 35
      maxIdle: 10
      maxWait : 100000
      testOnBorrow : true

  #spring:
#  datasource:
#    name: mysql_${project}
#    type: com.alibaba.druid.pool.DruidDataSource
#    #druid相关配置
#    druid:
#      #监控统计拦截的filters
#      filters: stat
#      driver-class-name: com.mysql.jdbc.Driver
#      #基本属性
#      url: jdbc:mysql://127.0.0.1:3306/${project}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: root
#      password: root
#      #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20

#  thymeleaf:
#    prefix: classpath:/templates/thymeleaf/
#    suffix: .html
#    mode: HTML
#    encoding: utf-8
#    servlet:
#      content-type: text/html
#    cache: false  #生产环境下需为true

  #mybatis:
  #  type-aliases-package: com.dcim.medusha.model
  #  mapper-locations: classpath:mapper/*.xml
  #mybatis
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.dcim.medusha.model
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 3
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 9
#    logic-not-delete-value: 0
#    #自定义SQL注入器
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    #自定义填充策略接口实现
#    meta-object-handler: com.dcim.medusha.common.handler.MyMetaObjectHandler
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false



  #pagehelper
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#  returnPageInfo: check

